package tbooop.model.enemy.impl;

import tbooop.commons.api.Point2d;
import tbooop.commons.api.Vector2d;
import tbooop.commons.api.AbstractProjectile;
import tbooop.model.core.api.GameObject;
import tbooop.model.core.api.GameTag;
import tbooop.model.player.api.Player;

/**
 * An enemy projectile is generated by enemy objects and will damage the player
 * if a physical contact occurs.
 */
public class EnemyProjectile extends AbstractProjectile {

    private static final int DAMAGE_AMOUNT = 1;
    /**
     * Creates an instance of an enemy projectile.
     * 
     * @param direction the projectile's direction
     * @param initialPoint the starting position
     * @param velocity the projectile's velocity
     */
    protected EnemyProjectile(final Vector2d direction, final Point2d initialPoint, final double velocity) {
        super(direction, initialPoint, velocity);
    }

    /** {@inheritDoc} */
    @Override
    public void disappear() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'disappear'");
    }

    /** {@inheritDoc} */
    @Override
    public void onCollision(final GameObject gameObj) {
        if (gameObj.getTag().equals(GameTag.PLAYER) && gameObj instanceof Player) {
            ((Player) gameObj).takeDamage(DAMAGE_AMOUNT);
        }
    }

}
