package tbooop.model.enemy.impl;

import tbooop.commons.Point2d;
import tbooop.commons.Vector2d;
import tbooop.commons.api.AbstractProjectile;
import tbooop.model.core.api.GameObject;

/**
 * An enemy projectile is generated by enemy objects and will damage the player
 * if a physical contact occurs.
 */
public class EnemyProjectile extends AbstractProjectile {

    /**
     * Creates an instance of an enemy projectile.
     * 
     * @param direction the projectile's direction
     * @param initialPoint the starting position
     * @param velocity the projectile velocity
     */
    protected EnemyProjectile(final Vector2d direction, final Point2d initialPoint, final double velocity) {
        super(direction, initialPoint, velocity);
        //TODO Auto-generated constructor stub
    }

    /** {@inheritDoc} */
    @Override
    public void disappear() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'disappear'");
    }

    /** {@inheritDoc} */
    @Override
    public void onCollision(final GameObject gameObj) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'onCollision'");
    }

    /** {@inheritDoc} */
    @Override
    public void updateState(final long deltaTime) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'updateState'");
    }

}
