/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tbooop.appl;

import java.util.logging.Logger;

import javafx.application.Application;
import tbooop.view.TestWindow;
import tbooop.view.View;

/** Main application entry-point's class. */

public final class App {
    private App() {
    }

    /**
     * Main application entry-point.
     * 
     * @param args
     */

    public static void main(final String[] args) {
        final Logger logger = Logger.getLogger(App.class.getName());
        logger.info("Main thread started.");
        Application.launch(TestWindow.class, args);
    }
}
